name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Run E2E testes
        run: npx xypress run
